/* Catálogo local: array de objetos.
   Completar cada producto con: id, nombre, precio, imagen, descripcion,
   destacados, detalles de fabricación, etc.
*/

const PRODUCTOS = [
  {
    id: 1,
    nombre: "Aparador Uspallata",
    descripcion: "Aparador de seis puertas fabricado en nogal sostenible con tiradores metálicos en acabado latón. Su silueta minimalista realza el veteado natural de la madera, creando una pieza que combina funcionalidad y elegancia atemporal para espacios contemporáneos.",
    medidas: "180 × 45 × 75 cm",
    materiales: "Nogal macizo FSC®, herrajes de latón",
    acabado: "Aceite natural ecológico",
    peso: "68 kg",
    caracteristica_extra: "Capacidad: 6 compartimentos interiores",
    precio: 850000,
    imagen: "img/Aparador Uspallata.png",
    destacado: true
  },
  {
    id: 2,
    nombre: "Biblioteca Recoleta",
    descripcion: "Sistema modular de estantes abierto que combina estructura de acero Sage Green y repisas en roble claro. Perfecta para colecciones y objetos de diseño, su diseño versátil se adapta a cualquier espacio contemporáneo con elegancia funcional.",
    medidas: "100 × 35 × 200 cm",
    materiales: "Estructura de acero, estantes de roble",
    acabado: "Laca mate ecológica",
    peso: "45 kg por estante",
    caracteristica_extra: "Modulares: 5 estantes ajustables",
    precio: 620000,
    imagen: "img/Biblioteca Recoleta.png",
    destacado: false
  },
  {
    id: 3,
    nombre: "Butaca Mendoza",
    descripcion: "Butaca tapizada en bouclé Dusty Rose con base de madera de guatambú. El respaldo curvo abraza el cuerpo y ofrece máximo confort, mientras que su diseño orgánico aporta calidez y sofisticación a cualquier ambiente contemporáneo.",
    medidas: "80 × 75 × 85 cm",
    materiales: "Guatambú macizo, tela bouclé",
    acabado: "Cera vegetal, tapizado premium",
    peso: "N/A",
    caracteristica_extra: "Tapizado repelente al agua y manchas",
    precio: 450000,
    imagen: "img/Butaca Mendoza.png",
    destacado: true
  },
  {
    id: 4,
    nombre: "Sillón Copacabana",
    descripcion: "Sillón lounge en cuero cognac con base giratoria en acero Burnt Sienna. Inspirado en la estética brasilera moderna de los 60, combina comodidad excepcional con un diseño icónico que trasciende tendencias y épocas.",
    medidas: "90 × 85 × 95 cm",
    materiales: "Cuero curtido vegetal, acero pintado",
    acabado: "Cuero anilina premium",
    peso: "N/A",
    caracteristica_extra: "Rotación 360° silenciosa y suave",
    precio: 980000,
    imagen: "img/Sillón Copacabana.png",
    destacado: true
  },
  {
    id: 5,
    nombre: "Mesa de Centro Araucaria",
    descripcion: "Mesa de centro con sobre circular de mármol Patagonia y base de tres patas en madera de nogal. Su diseño minimalista se convierte en el punto focal perfecto para cualquier sala de estar contemporánea, combinando la frialdad del mármol con la calidez de la madera.",
    medidas: "90 × 90 × 45 cm",
    materiales: "Sobre de mármol Patagonia, patas de nogal",
    acabado: "Mármol pulido, aceite natural en madera",
    peso: "42 kg",
    caracteristica_extra: "Carga máxima 25 kg distribuidos",
    precio: 710000,
    imagen: "img/Mesa de Centro Araucaria.png",
    destacado: false
  },
  {
    id: 6,
    nombre: "Mesa de Noche Aconcagua",
    descripcion: "Mesa de noche con cajón oculto y repisa inferior en roble certificado FSC®. Su diseño limpio y funcional permite convivir con diferentes estilos de dormitorio, ofreciendo almacenamiento discreto y elegante para objetos personales.",
    medidas: "45 × 35 × 60 cm",
    materiales: "Roble macizo FSC®, herrajes soft-close",
    acabado: "Barniz mate de poliuretano",
    peso: "N/A",
    caracteristica_extra: "Almacenamiento: 1 cajón + repisa inferior",
    precio: 250000,
    imagen: "img/Mesa de Noche Aconcagua.png",
    destacado: false
  },
  {
    id: 7,
    nombre: "Sofá Patagonia",
    descripcion: "Sofá de tres cuerpos tapizado en lino Warm Alabaster con patas cónicas de madera. Los cojines combinan espuma de alta resiliencia con plumón reciclado, ofreciendo comodidad duradera y sostenible para el hogar moderno.",
    medidas: "220 × 90 × 80 cm",
    materiales: "Madera de eucalipto certificada FSC®, Lino 100% natural premium",
    acabado: "N/A",
    peso: "N/A",
    caracteristica_extra: "Relleno: Espuma HR + plumón reciclado",
    precio: 1450000,
    imagen: "img/Sofá Patagonia.png",
    destacado: true
  },
  {
    id: 8,
    nombre: "Mesa Comedor Pampa",
    descripcion: "Mesa extensible de roble macizo con tablero biselado y sistema de apertura suave. Su diseño robusto y elegante se adapta perfectamente a reuniones íntimas o grandes celebraciones familiares, extendiéndose de 6 a 10 comensales.",
    medidas: "160-240 × 90 × 75 cm",
    materiales: "Roble macizo FSC®, mecanismo alemán",
    acabado: "Aceite-cera natural",
    peso: "N/A",
    caracteristica_extra: "Extensión: Sistema de mariposa central",
    precio: 1100000,
    imagen: "img/Mesa Comedor Pampa.png",
    destacado: false
  },
  {
    id: 9,
    nombre: "Sillas Córdoba",
    descripcion: "Set de cuatro sillas apilables en contrachapado moldeado de nogal y estructura tubular pintada en Sage Green. Su diseño ergonómico y materiales de calidad garantizan comodidad y durabilidad en el uso diario, perfectas para comedores contemporáneos.",
    medidas: "45 × 52 × 80 cm (cada una)",
    materiales: "Contrachapado nogal, tubo de acero",
    acabado: "Laca mate, pintura epoxi",
    peso: "N/A",
    caracteristica_extra: "Apilables: Hasta 6 sillas. Incluye Set de 4 sillas",
    precio: 520000,
    imagen: "img/Sillas Córdoba.png",
    destacado: false
  },
  {
    id: 10,
    nombre: "Escritorio Costa",
    descripcion: "Escritorio compacto con cajón organizado y tapa pasacables integrada en bambú laminado. Ideal para espacios de trabajo en casa, combina funcionalidad moderna con estética minimalista y sostenible, perfecto para el trabajo remoto.",
    medidas: "120 × 60 × 75 cm",
    materiales: "Bambú laminado, herrajes ocultos",
    acabado: "Laca mate resistente",
    peso: "N/A",
    caracteristica_extra: "Almacenamiento: 1 cajón con organizador",
    precio: 380000,
    imagen: "img/Escritorio Costa.png",
    destacado: false
  },
  {
    id: 11,
    nombre: "Silla de Trabajo Belgrano",
    descripcion: "Silla ergonómica regulable en altura con respaldo de malla transpirable y asiento tapizado en tejido reciclado. Diseñada para largas jornadas de trabajo con máximo confort y apoyo lumbar, ideal para oficinas en casa y espacios de coworking.",
    medidas: "60 × 60 × 90-100 cm",
    materiales: "Malla técnica, tejido reciclado",
    acabado: "Base cromada, tapizado premium",
    peso: "N/A",
    caracteristica_extra: "Regulación: Altura + inclinación respaldo",
    precio: 410000,
    imagen: "img/Silla de Trabajo Belgrano.png",
    destacado: false
  }
];
